name: CI Build
on:
  push:
    branches:
      - master

jobs:
  build-image:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          # fetch-depth: 0 needed for `git rev-list --count` to work properly
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'
      - 
        name: Push Image
        run: make push-latest
