name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.push-image.outputs.image }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          # fetch-depth: 0 needed for `git rev-list --count` to work properly
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'
      - 
        name: Push Image
        id: push-image
        run: make push-latest

  deploy-stage:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      -
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GUESTBOOK_DEPLOY_KEY }}
      -
        uses: imranismail/setup-kustomize@v1
      -
        name: Kustomize
        run: |
          git config --global user.name "Deploy Bot"
          git config --global user.email "no-reply@akuity.io"
          git clone git@github.com:akuity/guestbook-deploy.git
          cd guestbook-deploy/env/stage
          kustomize edit set image ${{ needs.build-image.outputs.image }}
          git commit -a -m "Deploy stage: ${{ needs.build-image.outputs.image }}"
          git push

  deploy-prod:
    needs: [build-image, deploy-stage]
    runs-on: ubuntu-latest
    steps:
      -
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GUESTBOOK_DEPLOY_KEY }}
      -
        uses: imranismail/setup-kustomize@v1
      -
        name: Kustomize
        run: |
          git config --global user.name "Deploy Bot"
          git config --global user.email "no-reply@akuity.io"
          git clone git@github.com:akuity/guestbook-deploy.git
          cd guestbook-deploy/env/prod
          kustomize edit set image ${{ needs.build-image.outputs.image }}
          git commit -a -m "Deploy prod: ${{ needs.build-image.outputs.image }}"
          git push
